ipynb-filters: [nbdev_filter]

project:
  type: website
  output-dir: _docs
  preview:
    port: 3000
    browser: false

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 4

website:
  title: "PromptGPT"
  site-url: "https://DanNguyenN.github.io/PromptGPT"
  description: "This will generate prompt at the level of a prompt egineer make it easier for new people start wokring model like ChatGPT in their life"
  twitter-card: true
  open-graph: true
  repo-branch: master
  repo-url: "https://github.com/DanNguyenN/PromptGPT"
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    right:
      - icon: github
        href: "https://github.com/DanNguyenN/PromptGPT"
  sidebar:
    style: "floating"

metadata-files: 
  - sidebar.yml
  - custom.yml
