steps:
#! Download the model to embed it into the image
#! - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#!   args: ['gsutil', 'cp','-r', 'gs://dolly-model-test/models', '.']
#!   id: 'download-model'
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/aerobic-gantry-387923/promptgpt/promptgpt_api', '.']
  #! waitFor: ['download-model']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/aerobic-gantry-387923/promptgpt/promptgpt_api']

images:
- us-central1-docker.pkg.dev/aerobic-gantry-387923/promptgpt/promptgpt_api